apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: demo
  namespace: dev
  labels:
    chart: podinfo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:*
spec:
  releaseName: demo-dev
  chart:
    git: https://github.com/armkung/gitops.git
    path: charts/api
    ref: master
  values:
    release: dev